apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
labels:
  monitoring: victoria-stack
resources:
  - namespace.yaml
  - victoria-metrics-service.yaml
  - victoria-metrics-statefulset.yaml
  - victoria-logs-service.yaml
  - victoria-logs-deployment.yaml
