apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-logs
  labels:
    app: victoria-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-logs
  template:
    metadata:
      labels:
        app: victoria-logs
    spec:
      containers:
        - name: victoria-logs
          image: victoriametrics/victoria-logs:v1.41.0
          args:
            - -httpListenAddr=:8080
            - -search.listen-addr=:7070
            - -search.store-paths=/victoria-logs-data
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 7070
              name: search
          volumeMounts:
            - name: data
              mountPath: /victoria-logs-data
      volumes:
        - name: data
          emptyDir: {}
