# Copy or replace these with VM config
#
# This file was originally generated by ‘nixos-generate-config’.
# Replace its contents with the hardware-configuration.nix
# from your VM.
/*
EMPTY
*/
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {}
