{...}: {
  # Import hardware configuration generated by nixos-generate-config.
  imports = [
    ./hardware-configuration.nix
  ];

  # Node identity + static network settings.
  # Ensure the IP matches your Proxmox VM configuration.
  custom.networking = {
    hostName = "k3s-worker-2";
    interface = "ens18";
    staticIPv4 = "192.168.100.162";
    prefixLength = 24;
    gateway = "192.168.100.1";
    nameservers = ["1.1.1.1" "8.8.8.8"];
  };

  custom.role = "worker";

}
