{ ... }:

{
  # Import hardware configuration generated by nixos-generate-config.
  imports = [
    ./hardware-configuration.nix
  ];

  # Node identity + static network settings.
  # Ensure the IP matches your Proxmox VM configuration.
  custom.networking = {
    hostName = "k3s-worker-2";
    staticIPv4 = "192.168.100.162";
  };

  # Workers do not require Git identity; keep disabled.
  custom.git.enable = false;

  # SSH configuration
  #
  # Root login + password auth are enabled only for convenience.
  # This is NOT recommended for production worker nodes.
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "yes";       # temporary: allows root login
      PasswordAuthentication = true; # temporary: allow SSH password logins
    };
  };
}
