{...}: {
  # Import hardware configuration generated by nixos-generate-config.
  imports = [
    ./hardware-configuration.nix
  ];

  # Basic node identity + static IP.
  # Adjust these to match your Proxmox VM network.
  custom.networking = {
    hostName = "k3s-worker-1";
    staticIPv4 = "192.168.100.161";
  };

  # Workers generally do not need Git identity,
  # so this is intentionally disabled.
  custom.git.enable = false;

  # SSH access settings
  #
  # Workers typically do NOT require password or root login.
  # These are enabled only for convenience during setup.
  # For production, disable password auth and root login.
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "yes"; # temporary: allows root login
      PasswordAuthentication = true; # temporary: password authentication enabled
    };
  };
}
