{...}: {
  # Import hardware configuration generated by nixos-generate-config.
  imports = [
    ./hardware-configuration.nix
  ];

  # Node identity + static network settings.
  # Ensure the IP matches your Proxmox VM configuration.
  custom.networking = {
    hostName = "k3s-worker-2";
    interface = "ens18";
    staticIPv4 = "192.168.100.162";
    prefixLength = 24;
    gateway = "192.168.100.1";
    nameservers = ["1.1.1.1" "8.8.8.8"];
  };

  # Git identity (override with real values or disable if unused).
  custom.git = {
    enable = true;
    email = "your_email@example.com";
    username = "your_username";
    fullName = "Your Name";
  };

  # SSH configuration
  #
  # Root login + password auth are enabled only for convenience.
  # This is NOT recommended for production worker nodes.
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "yes"; # temporary: allows root login
      PasswordAuthentication = true; # temporary: allow SSH password logins
    };
  };
}
