apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-gateway
rules:
- apiGroups: [""]
  resources:
    - services
    - endpoints
    - secrets
    - nodes
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups: [""]
  resources:
    - events
    - pods
  verbs:
    - create
    - patch
    - update
    - list
    - watch
- apiGroups:
    - networking.k8s.io
    - extensions
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - gateway.networking.k8s.io
  resources:
    - gateways
    - gatewayclasses
    - referencegrants
    - httproutes
    - tlsroutes
    - tcproutes
    - udproutes
    - grpcroutes
  verbs:
    - get
    - list
    - watch
