apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-gateway
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      serviceAccountName: traefik-gateway
      containers:
        - name: traefik
          image: traefik:2.11.11
          args:
            - --providers.kubernetesgateway
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --log.level=INFO
            - --api.insecure=true
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
