apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portainer
resources:
  - https://downloads.portainer.io/ce-lts/portainer-lb.yaml
patchesStrategicMerge:
  - service-clusterip.yaml
