apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - portainer-lb.yaml
patches:
  - target:
      kind: Service
      name: portainer
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: portainer
        namespace: portainer
      spec:
        type: ClusterIP
patchesStrategicMerge:
  - portainer-resources.yaml
