apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: cilium-system
data:
  auto-direct-node-routes: "true"
  enable-endpoint-routes: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-conntrack: "true"
  kube-proxy-replacement: "strict"
  tunnel: "vxlan"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
