apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium-system
resources:
  - namespace.yaml
  - https://github.com/cilium/cilium/releases/download/v1.15.3/cilium.yaml
patchesStrategicMerge:
  - cilium-config.yaml
