apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - namespace.yaml
  - jenkins-serviceaccount.yaml
  - jenkins-clusterrole.yaml
  - jenkins-clusterrolebinding.yaml
  - jenkins-pvc.yaml
  - jenkins-deployment.yaml
  - jenkins-service.yaml
patches:
  - path: jenkins-resources.yaml
    target:
      version: v1
      kind: Deployment
      name: jenkins
      namespace: jenkins
