apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - namespace.yaml
  - jenkins-serviceaccount.yaml
  - jenkins-clusterrole.yaml
  - jenkins-clusterrolebinding.yaml
  - jenkins-pvc.yaml
  - jenkins-deployment.yaml
  - jenkins-service.yaml
  - jenkins-resources.yaml
